export const CORE_SERVICES = [
  'ec2',
  's3',
  'lambda',
  'dynamodb',
  'sqs',
  'sns',
  'iam',
] as const

export const SERVICE_META: Record<string, { label: string; accent: string }> = {
  ec2: { label: 'EC2', accent: '#f58536' },
  s3: { label: 'S3', accent: '#3f8624' },
  lambda: { label: 'Lambda', accent: '#e87722' },
  dynamodb: { label: 'DynamoDB', accent: '#4053d6' },
  sqs: { label: 'SQS', accent: '#e31c5f' },
  sns: { label: 'SNS', accent: '#dd344c' },
  iam: { label: 'IAM', accent: '#d13212' },
  apigateway: { label: 'API Gateway', accent: '#a166ff' },
  apigatewayv2: { label: 'API Gateway v2', accent: '#a166ff' },
  events: { label: 'EventBridge', accent: '#e7157b' },
  scheduler: { label: 'EventBridge Scheduler', accent: '#e7157b' },
  pipes: { label: 'EventBridge Pipes', accent: '#e7157b' },
  stepfunctions: { label: 'Step Functions', accent: '#e7157b' },
  logs: { label: 'CloudWatch Logs', accent: '#fe4f64' },
  cloudwatch: { label: 'CloudWatch Metrics', accent: '#fe4f64' },
  rum: { label: 'CloudWatch RUM', accent: '#fe4f64' },
  kms: { label: 'KMS', accent: '#dd344c' },
  secretsmanager: { label: 'Secrets Manager', accent: '#dd344c' },
  vpc: { label: 'VPC', accent: '#8c4fff' },
  ecs: { label: 'ECS', accent: '#e87722' },
  ecr: { label: 'ECR', accent: '#e87722' },
  elbv2: { label: 'ALB / ELB v2', accent: '#8c4fff' },
  route53: { label: 'Route 53', accent: '#8c4fff' },
  cloudformation: { label: 'CloudFormation', accent: '#e87722' },
  sts: { label: 'STS', accent: '#d13212' },
  ssm: { label: 'SSM', accent: '#e31c5f' },
  s3tables: { label: 'S3 Tables', accent: '#3f8624' },
  s3vectors: { label: 'S3 Vectors', accent: '#3f8624' },
  dynamodbstreams: { label: 'DynamoDB Streams', accent: '#4053d6' },
  organizations: { label: 'Organizations', accent: '#d13212' },
  'cognito-idp': { label: 'Cognito', accent: '#d13212' },
  cloudhsmv2: { label: 'CloudHSM v2', accent: '#dd344c' },
  kinesis: { label: 'Kinesis', accent: '#e31c5f' },
  kinesisanalyticsv2: { label: 'Managed Flink', accent: '#e31c5f' },
  swf: { label: 'SWF', accent: '#e7157b' },
  guardduty: { label: 'GuardDuty', accent: '#dd344c' },
  elasticache: { label: 'ElastiCache', accent: '#4053d6' },
  memorydb: { label: 'MemoryDB', accent: '#4053d6' },
  rds: { label: 'RDS', accent: '#3f8624' },
  kafka: { label: 'MSK', accent: '#e31c5f' },
  mq: { label: 'Amazon MQ', accent: '#e31c5f' },
  mwaa: { label: 'MWAA', accent: '#e87722' },
  athena: { label: 'Athena', accent: '#3f8624' },
  glue: { label: 'Glue', accent: '#e87722' },
  neptune: { label: 'Neptune', accent: '#4053d6' },
  docdb: { label: 'DocumentDB', accent: '#3f8624' },
  emr: { label: 'EMR', accent: '#e87722' },
  'emr-serverless': { label: 'EMR Serverless', accent: '#e87722' },
  firehose: { label: 'Data Firehose', accent: '#e31c5f' },
  efs: { label: 'EFS', accent: '#8c4fff' },
  lightsail: { label: 'Lightsail', accent: '#f58536' },
  acm: { label: 'ACM', accent: '#dd344c' },
  'resource-explorer-2': { label: 'Resource Explorer', accent: '#8b9aab' },
  ses: { label: 'SES', accent: '#e31c5f' },
  sesv2: { label: 'SES v2', accent: '#e31c5f' },
  opensearch: { label: 'OpenSearch', accent: '#e87722' },
  appconfig: { label: 'AppConfig', accent: '#e87722' },
  appsync: { label: 'AppSync', accent: '#a166ff' },
  eks: { label: 'EKS', accent: '#e87722' },
  wafv2: { label: 'WAF v2', accent: '#dd344c' },
  autoscaling: { label: 'Auto Scaling', accent: '#f58536' },
  'application-autoscaling': { label: 'Application Auto Scaling', accent: '#f58536' },
  elasticbeanstalk: { label: 'Elastic Beanstalk', accent: '#3f8624' },
  codebuild: { label: 'CodeBuild', accent: '#e87722' },
  batch: { label: 'AWS Batch', accent: '#e87722' },
  codedeploy: { label: 'CodeDeploy', accent: '#e87722' },
  codepipeline: { label: 'CodePipeline', accent: '#e87722' },
  backup: { label: 'AWS Backup', accent: '#8b9aab' },
  fis: { label: 'AWS FIS', accent: '#dd344c' },
  cloudfront: { label: 'CloudFront', accent: '#8c4fff' },
  servicediscovery: { label: 'Cloud Map', accent: '#8c4fff' },
  config: { label: 'AWS Config', accent: '#8b9aab' },
  cloudtrail: { label: 'CloudTrail', accent: '#8b9aab' },
  transcribe: { label: 'Transcribe', accent: '#a166ff' },
  cur: { label: 'Cost and Usage Reports', accent: '#e7c36a' },
  'bcm-data-exports': { label: 'BCM Data Exports', accent: '#e7c36a' },
  transfer: { label: 'Transfer Family', accent: '#3f8624' },
  iot: { label: 'IoT Core', accent: '#8c4fff' },
  signin: { label: 'AWS Sign-In', accent: '#8b9aab' },
  'lambda-microvms': { label: 'Lambda MicroVMs', accent: '#e87722' },
  cloudcontrol: { label: 'Cloud Control API', accent: '#8b9aab' },
  'rds-data': { label: 'RDS Data API', accent: '#3f8624' },
  appconfigdata: { label: 'AppConfig Data', accent: '#e87722' },
  'bedrock-runtime': { label: 'Bedrock Runtime', accent: '#a166ff' },
  'bedrock-agentcore-control': { label: 'Bedrock AgentCore Control', accent: '#a166ff' },
  'bedrock-agentcore': { label: 'Bedrock AgentCore', accent: '#a166ff' },
  resourcegroupstaggingapi: { label: 'Resource Groups Tagging', accent: '#8b9aab' },
  textract: { label: 'Textract', accent: '#a166ff' },
  pricing: { label: 'Pricing', accent: '#e7c36a' },
  ce: { label: 'Cost Explorer', accent: '#e7c36a' },
  'iot-data': { label: 'IoT Data', accent: '#8c4fff' },
}

export const ALL_SERVICES = Object.keys(SERVICE_META)

export function serviceLabel(service: string) {
  return SERVICE_META[service]?.label ?? service
}

export function servicesFromInventory(services: Record<string, number> | undefined) {
  const keys = new Set([...ALL_SERVICES, ...Object.keys(services ?? {})])
  return [...keys].sort((a, b) => {
    const left = services?.[a] ?? 0
    const right = services?.[b] ?? 0
    if (left !== right) return right - left
    return serviceLabel(a).localeCompare(serviceLabel(b))
  })
}
